## THIS FILE IS AUTOMATICALLY GENERATED BY SCAFFOLDLY ##
## CONFIG CAN BE CHANGED AT https://start.scaffold.ly ##

terraform {
  required_version = ">= 1.0.4, < 1.1.0"
  experiments      = [module_variable_optional_attrs]

  backend "remote" {
    workspaces {
      name = "scaffoldly-bootstrap"
    }
  }
}

variable "ROOT_EMAIL" {
  type        = string
  description = "Root email address"
}

variable "BOOTSTRAP_ORGANIZATION" {
  type        = string
  description = "GitHub/Terraform Cloud Organization"
}
