name: Prerelease

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
      - uses: scaffoldly/archetect-render-action@v1
        with:
          source: "."
          destination: "${{ runner.temp }}/rendered"
          options: "-s overwrite -a nonlive_domain=example.dev -a live_domain=example.com"
          commit: "false"
      - run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate
        env:
          TF_VAR_ROOT_EMAIL: ci+archetype-scaffoldly-bootstrap@scaffold.ly
          TF_VAR_BOOTSTRAP_ORGANIZATION: archetype-scaffoldly-bootstrap
          TF_VAR_BOOTSTRAP_AWS_ACCOUNT_ID: 000000000000
        working-directory: "${{ runner.temp }}/rendered"
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: sly.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}