name: Prerelease

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        archetect-options:
          - "-a nonlive_domain=example.dev -a live_domain=example.com"
          - "-a nonlive_domain=example.dev -a live_domain=example.com -a aws=true -a serverless_api_repos=example-sls-rest-api"
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
      - uses: scaffoldly/archetect-render-action@1.0.5
        with:
          source: "."
          destination: "${{ runner.temp }}/rendered"
          options: ${{ matrix.archetect-options }}
          commit: "false"
      - run: |
          terraform init -backend=false
          terraform fmt -check
          terraform validate
        env:
          TF_VAR_ROOT_EMAIL: ci+archetype-scaffoldly-bootstrap@scaffold.ly
          TF_VAR_BOOTSTRAP_ORGANIZATION: archetype-scaffoldly-bootstrap
          TF_VAR_BOOTSTRAP_AWS_ACCOUNT_ID: 000000000000
        working-directory: "${{ runner.temp }}/rendered"
  prerelease:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: sly.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}