name: Prerelease

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  TF_VAR_ROOT_EMAIL: ci+archetype-scaffoldly-bootstrap@scaffold.ly
  TF_VAR_BOOTSTRAP_ORGANIZATION: archetype-scaffoldly-bootstrap
  TF_VAR_BOOTSTRAP_AWS_ACCOUNT_ID: 000000000000

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        archetect-options:
          - "-s base -s github"
          - "-s base -s github -s aws -s aws-base -a nonlive-domain=example.dev -a live-domain=example.com"
          - "-s base -s github -s aws -s aws-base -s serverless-api -a nonlive-domain=example.dev -a live-domain=example.com -a serverless-api-repos=example-sls-rest-api"
          # todo layering test
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
      - uses: scaffoldly/archetect-render-action@v1
        with:
          source: "."
          destination: "${{ runner.temp }}/rendered"
          options: "-s overwrite ${{ matrix.archetect-options }}"
          commit: "false"
      - run: terraform init -backend=false
        working-directory: "${{ runner.temp }}/rendered"
      - run: terraform fmt -check
        working-directory: "${{ runner.temp }}/rendered"
      - run: terraform validate
        working-directory: "${{ runner.temp }}/rendered"
  prerelease:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: sly.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}